// Generated by CoffeeScript 1.3.3
(function() {
  var hello, port;

  port = Number(process.env.PORT || 3000);

  hello = require('zappajs')(port, function() {
    this.get({
      '/': function() {
        return this.redirect('/hello/world');
      }
    });
    this.get({
      '/hello': function() {
        return this.render({
          question: {}
        });
      }
    });
    this.get({
      '/hello/:name': function() {
        return this.render({
          greeting: {
            "name": this.params.name
          }
        });
      }
    });
    this.view({
      greeting: function() {
        this.title = 'Greetings to the people';
        h1("Greeting");
        return p("Hello " + this.name);
      }
    });
    this.view({
      question: function() {
        this.title = 'Who are you?';
        h1("Who are you?");
        return form({
          method: "POST",
          action: '/hello'
        }, function() {
          input({
            type: "text"
          });
          return button({
            type: "submit"
          }, function() {
            return "Greet";
          });
        });
      }
    });
    this.view({
      layout: function() {
        doctype(5);
        return html(function() {
          head(function() {
            title(this.title);
            return link({
              rel: "stylesheet",
              href: "/base.css"
            });
          });
          return body(this.body);
        });
      }
    });
    return this.css({
      '/base.css': 'body {\n	margin-left: auto;\n	margin-right: auto;\n	width:80%;\n	font-family: sans-serif;\n	margin-top: 2em;\n}'
    });
  });

}).call(this);
